NumPy Basics and Introduction

This notebook introduces NumPy, a core Python library for numerical computing.


In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
L=[1,2,3,4,5]
L

[1, 2, 3, 4, 5]

In [4]:
arr1 = np.array(L)
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr3 = np.array([[[1,2,3,4],[22,3,2,4]],[[4,1,5,6],[5,77,5,8]]])
arr3

array([[[ 1,  2,  3,  4],
        [22,  3,  2,  4]],

       [[ 4,  1,  5,  6],
        [ 5, 77,  5,  8]]])

In [7]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [8]:
arr1.shape

(5,)

In [9]:
arr2.shape
arr3.shape

(2, 2, 4)

In [10]:
arr2[:,1]

array([2, 5])

In [11]:
arr2[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [12]:
np.random.randint(1,4,(2,3))

array([[1, 3, 1],
       [1, 2, 1]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
mat1=np.array([[1,2,3],[2,3,6]])
mat2=np.array([[12,5,3],[1,32,26]])
mat1+mat2

array([[13,  7,  6],
       [ 3, 35, 32]])

In [16]:
mat4=np.array([[1,3],[2,4],[5,7]])
mat1 @ mat4

array([[20, 32],
       [38, 60]])